# Generated by Django 3.2 on 2023-06-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230619_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='tags',
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='api.tag'),
        ),
    ]
