# Generated by Django 3.2 on 2023-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_idea_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="aveerage_rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
