name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEBUG: False
  SECRET_KEY: "Not Applicable"
  ALLOWED_HOSTS: "127.0.0.1 localhost"
  SITE_ID: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3

    - name: update-system-dependencies
      run: | 
        sudo apt-get update -y

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.8
        cache: "pip"

    - name: Install Dependencies
      run: |
        python3 -m venv venv projectSpark-api-v1/venv
        source projectSpark-api-v1/venv/bin/activate
        python -m pip install --upgrade pip==21.2.4
        pip install wheel
        pip install -r requirements.txt
        

    - name: Run Tests
      run: |
        source projectSpark-api-v1/venv/bin/activate
        cd projectSpark-api-v1
        python3 manage.py test
